### ISSUE TITLE
No connection selected

### ISSUE THREAD

**Issue by cretueusebiu** [tinkerun/tinkerun-vscode#1]
First of all really cool idea for running tinker.

But when I click Run I get this message:

![Screenshot_1](https://user-images.githubusercontent.com/1517945/115149026-ce1e4580-a06a-11eb-8191-95bba41ff3d8.png)

I have the [default](https://github.com/tinkerun/tinkerun-vscode/blob/master/resources/template/tinkerun.json) connection defined in `.tinkerun/tinkerun.json`. Also I'm on Windows 10.

**Comment by billyct** [comment]
I have not tested on windows. but I think it is caused by the path difference on windows.

**Comment by billyct** [comment]
I uploaded a new version. 😉 you can update in your vscode.

**Comment by cretueusebiu** [comment]
That fixed it. Thanks!
