### ISSUE TITLE
Getting Class not found error

### ISSUE THREAD

**Issue by h3mantD** [tinkerun/tinkerun-vscode#11]
![image](https://user-images.githubusercontent.com/50235905/194613121-8554d6c8-20b7-41b5-b276-3224c759abf2.png)
Getting class not found error.

**Comment by Andreas-Halemba** [comment]
@h3mantD how did you solve this?

**Comment by h3mantD** [comment]
@Andreas-Halemba 

To execute the code use `Tinkerun: Run` option..

<img width="376" alt="Screenshot 2024-10-02 at 4 12 26 PM" src="https://github.com/user-attachments/assets/81b1e329-aa1b-469d-a6a3-c37fa985f6bd">
