### ISSUE TITLE
"Cannot redeclare function"

### ISSUE THREAD

**Issue by nxmndr** [tinkerun/tinkerun-vscode#12]
Hi,

When I run a file twice or more, I have an error message saying that functions or classes "cannot be redeclared" / "already exists" : `Cannot redeclare f() in Psy Shell`, `Class named C already exists`. So I have to kill the shell manually every time.

I upgraded my system recently but I don't really know what triggered that change as I tested it with PHP 7 & 8.

Does it mean Tinkerun re-uses the same PsySH session ? Would it be feasible to kill it & start a new shell instead ?

Thank you

Versions :
MacOS : 11.5.2
VSCode : 1.73.1
Tinkerun 0.2.2
PHP : 7.4.32 & 8.0.26
Laravel : 8.83.23

**Comment by billyct** [comment]
> Does it mean Tinkerun re-uses the same PsySH session?

yes

> Would it be feasible to kill it & start a new shell instead?

<img src="https://user-images.githubusercontent.com/1612364/205662513-87a05e18-f0e8-4f2b-b28b-3ccc9a637a4b.png" alt="Kill terminal" width="200">

1. kill terminal
2. run it again 

References:

https://github.com/bobthecow/psysh/issues/416
