### ISSUE TITLE
An option to change shortcut

### ISSUE THREAD

**Issue by d-damien** [tinkerun/tinkerun-vscode#2]
I would like to make it possible to change the shortcut to run code.

Use case : incompatibility with VSCodeVim. Vim has Ctrl+R as "redo" action, and it's been a standard for decades.

Thank you.

**Comment by billyct** [comment]
the default shortcut is `Ctrl+R`, also you can bind yours:

1. open `Code -> Preferences -> Keyboard Shortcuts`
2. search `tinkerun.run`
3. bind your favorite shortcut

**Comment by d-damien** [comment]
My bad.
