### ISSUE TITLE
Give hand back to Tinker after running code

### ISSUE THREAD

**Issue by d-damien** [tinkerun/tinkerun-vscode#3]
When you run the code, Tinkerun displays the result, but does not give control back to Tinker. I understand the idea is you're supposed to modify the file, and re-run the code, but sometimes you want to write it directly in Tinker.

Use case 1 : running a long operation, you don't want to wait every time before you start writing after, using the Tinkerun results.

Use case 2 : I'd like to use Tinkerun files as init scripts for Tinker debugging sessions, e.g. the infamous `use Carbon\Carbon`, annoying to write every time.

Great work ; thank you !

**Comment by billyct** [comment]
maybe you are right.

how about something like this, when clicking the run button, two-panel appears, one panel for the result, and one for the original Tinker session?

<img width="1097" alt="screenshot" src="https://user-images.githubusercontent.com/1612364/115365920-677a6280-a1f7-11eb-9a08-60b3c7c6dc22.png">

**Comment by d-damien** [comment]
I'm surprised Tinker doesn't let you do both in one session. But if that's the only option, it's fine I think. If I can have my init scripts loaded when starting Tinker-ing, I'm happy :)

**Comment by billyct** [comment]
Now you can hand it back to Tinker by just press `Enter` in the result panel.
I uploaded the new version, 😉 try to update it in your vscode.

**Comment by d-damien** [comment]
Awesome, thank you :)
